from datetime import datetime, timezone
import requests


class ExecutiveNotificationBridge:

    def __init__(
        self,
        evolution_url: str,
        api_key: str,
        instance: str,
        target: str,
    ):
        self.evolution_url = evolution_url
        self.api_key = api_key
        self.instance = instance
        self.target = target


    def build_message(
        self,
        status: str,
        risk_score: float,
        decision_score: float,
        confidence: float,
        action: str,
    ):

        return f"""
🚨 SS4TS EXECUTIVE DECISION ALERT

Status:
{status}

Risk Score:
{risk_score}/100

Decision Score:
{decision_score}/100

Confidence:
{confidence}%

Recommended Action:
{action}

Time:
{datetime.now(timezone.utc)}

Generated by:
SS4TS NOC Intelligence Engine
"""


    def send_whatsapp(self, message: str):

        url = (
            f"{self.evolution_url}/message/sendText/"
            f"{self.instance}"
        )

        headers = {
            "apikey": self.api_key,
            "Content-Type": "application/json",
        }

        payload = {
            "number": self.target,
            "text": message,
        }


        response = requests.post(
            url,
            json=payload,
            headers=headers,
            timeout=10,
        )

        return {
            "status_code": response.status_code,
            "response": response.json()
            if response.text
            else {}
        }
